service: pdf-generator

frameworkVersion: '3'

useDotenv: true

custom:
  bucket: test-files-678kph
  esbuild:
    bundle: true
    minify: false
    exclude: ['aws-sdk', 'pdfkit']

provider:
  name: aws
  runtime: nodejs16.x
  # Default region (default: us-east-1)
  region: eu-west-1
  # Duration for CloudWatch log retention (default: forever)
  logRetentionInDays: 14
  iam:
    # configure the role that will be created by Serverless (simplest):
    role:
      # Add statements to the IAM role to give permissions to Lambda functions
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: 'arn:aws:s3:::${self:custom.bucket}/*'

plugins:
  - serverless-esbuild

# Optional deployment packaging configuration
package:
  # Directories and files to include in the deployed package
  patterns:
    - lib/**
    - handler.js
    - '!layer/**'
    - '!.husky/**'
    - '!README.md'
    - '!LICENSE'
    - '!.prettierrc'
    - '!.eslintignore'
    - '!.eslintrc.js'
    - '!run.js'
  # Package each function as an individual artifact (default: false)
  individually: true
  # Automatically exclude NPM dev dependencies from the deployed package (default: true)
  excludeDevDependencies: true

layers:
  Pdfkit:
    name: Pdfkit
    compatibleRuntimes:
      - nodejs14.x
      - nodejs16.x
    description: Required for Pdfkit
    package:
      artifact: layer/pdfkit-layer.zip

functions:
  generatePDF:
    layers:
      - { Ref: PdfkitLambdaLayer }
    handler: handler.generate
    events:
      - httpApi:
          path: /generatePDF
          method: post
    environment:
      BUCKET: ${self:custom.bucket}
      REGION: ${aws:region}
